### ISSUE TITLE
How to wire a SCART connector

### ISSUE THREAD

**Issue by robcross** [ikorb/gcvideo#10]
I see that the RGB lines are directly from the DAC. Do I need to put 330 uF caps in the SCART head? Do I any other components in the SCART head for proper signals?

**Comment by robcross** [comment]
For more clarification, I plan to build the gcvideo_lite_09 board and I would like to ensure the specifications are correct for the cable I want to purchase from retro_console_accessories.

**Comment by ikorb** [comment]
The DAC outputs the usual 0.7Vpp into a 75 ohm impedance input with no DC offset (so no capacitors). The H and V sync outputs are 3V LVCMOS outputs, CSync is the same but with a 100 ohm series resistor and it should be able to drive a standard 75-ohm video input.

**Comment by robcross** [comment]
Thank you! I'm still learning these things :+1:

**Comment by robcross** [comment]
Hi @ikorb, I just wanted to say thanks! I just installed my board today and it works like a charm. Beautiful RGB output without breaking the bank!
