### ISSUE TITLE
No video/led from carby after trying to update to 3.1

### ISSUE THREAD

**Issue by Titusp13** [ikorb/gcvideo#100]
Tried to update my carby to 3.1 via gc loader dol. Launched the flash tool from carby and dol from gc loader. Looked like it was updating but just hanged. Pressed back on carby IR and it seemed to power off/reset carby and now i have no led at all. No video at all either. Help?

**Comment by ikorb** [comment]
Do you get a picture if you hold down the button on the side of the carby (*) while turning on the console?

(*) Section "Carby Remote Training" on https://insurrectionindustries.com/carby-quick-start-guide/

**Comment by Titusp13** [comment]
> Do you get a picture if you hold down the button on the side of the carby (*) while turning on the console?
> 
> (*) Section "Carby Remote Training" on https://insurrectionindustries.com/carby-quick-start-guide/

Yeah it was my retrotink 5X.... couldnt get a signal at all. I then tried direct into PC monitor and got video and successfully flashed new firmware. And is now working on the Retrotink 5X again. Thanks for the help and wonderful gcvideo ikorb :)
