### ISSUE TITLE
[Feature Request/Enhancement] Crop output timings to 640x480 CVT standard timing for VGA CRT monitors

### ISSUE THREAD

**Issue by GK6475** [ikorb/gcvideo#101]
My GameCube currently will not fill the whole screen in 1:1 pixel aspect mode. Height adjustment fills the whole screen, but horizontal adjustment at 100% still leaves black bars. Could a 640x480 timing mode be implemented to increase compatibility with VGA CRTs?

**Comment by ikorb** [comment]
The FPGA used by GCVideo has relatively inflexible clocking logic, I don't think there is a useful way to generate the required pixel clock for a true 640x480 output from the 54MHz system clock with that chip.
