### ISSUE TITLE
Can't update from 3.0e Wii Dual

### ISSUE THREAD

**Issue by homebrewGT** [ikorb/gcvideo#102]
I have been trying to update but I get this error:

![PXL_20220905_042823509](https://user-images.githubusercontent.com/32716977/188360675-4bf91bda-da9a-41c2-8eaf-e7ef5bc009b9.jpg)

**Comment by homebrewGT** [comment]
Fixed, used this http://dansprojects.com/firmware/WiiDual/WiiDual1.1_3.1.zip for my update and it worked great!

**Comment by Jon8RFC** [comment]
Thanks for sharing your solution.
Just for reference, when did you purchase your Wii Dual?
