### ISSUE TITLE
HDMI Alternate mode

### ISSUE THREAD

**Issue by Bakuku** [ikorb/gcvideo#104]
Hello,

Is the GCvideo software capable of HDMI Alternate mode?

For a project I’m working on I’m looking into simplifying the number of connectors that are used on a Gamecube by having both POWER and AV running through a single cable.

I know GCvideo doesn’t really use the standard HDMI protocol, but could the software be adjusted to support such a feature? 
I’m guessing a redesign of the hardware is necessary to accommodate the feature.

Thank.

**Comment by ikorb** [comment]
If you mean the USB-C alternate mode for transmitting HDMI over the four diff pairs of a USB-C cable, that is completely out of scope for GCVideo and would need to be handled by the USB-C controller chip. Of course GCVideo does not implement HDMI, but given HDMI's backwards compatibility with DVI I suspect that GCVIdeo's DVI signal over this alt mode would work.

Are there any actual HDMI alt mode products on the market though? As far as I know everyone seems to use Displayport alt mode and converters to HDMI (if needed), which has the advantage that it needs fewer data pairs and can thus coexist with USB 3.0 over the same cable.

**Comment by Bakuku** [comment]
@ikorb 

https://www.ti.com/lit/an/slla333/slla333.pdf?ts=1669067275760&ref_url=https%253A%252F%252Fwww.google.com%252F

**Comment by ikorb** [comment]
https://www.notebookcheck.com/Der-Tod-von-HDMI-ueber-USB-Typ-C-Alt-Mode-und-mehr-Power-im-Kabel.679977.0.html
