### ISSUE TITLE
Question about wii HDMI device

### ISSUE THREAD

**Issue by 49studebaker** [ikorb/gcvideo#108]
This device uses ikorb’s GCvideo. The digital output signal is lossless.

https://electron-shepherd.com/products/ave-hdmi

Does the following device use ikorb’s GCvideo? Is it converting analog to digital or is the digital output signal lossless? Thanks.

https://share.temu.com/LfrFNdNGyI

**Comment by ShaneKent** [comment]
> This device uses ikorb’s GCvideo. The digital output signal is lossless.
> 
> https://electron-shepherd.com/products/ave-hdmi
> 
> Does the following device use ikorb’s GCvideo? Is it converting analog to digital or is the digital output signal lossless? Thanks.
> 
> https://share.temu.com/LfrFNdNGyI

I’m one of the developers for the AVE-HDMI.
Our product uses ikorb’s GCVideo for digital-to-digital conversion.  It does not perform analog-to-digital conversion.

**Comment by 49studebaker** [comment]
Does the second device I posted, use GCvideo or is it doing analog to digital conversion? Is it possible to get lossless digital output from the digital output port or do wires have to be soldered to the circuit board? Thanks.

**Comment by ShaneKent** [comment]
> Does the second device I posted, use GCvideo or is it doing analog to digital conversion? Is it possible to get lossless digital output from the digital output port or do wires have to be soldered to the circuit board? Thanks.

The second device you listed does not use GCVideo. It performs an analog-to-digital conversion. The Wii does not have a digital output port, so the only way to achieve a digital-to-digital conversion on the Wii is to do an internal mod installation.
