### ISSUE TITLE
[Feature Request/Enhancement] Improve Chroma Interpolation Feature

### ISSUE THREAD

**Issue by GK6475** [ikorb/gcvideo#109]
When I toggle Chroma Interpolation on, it does smooth the jaggies caused by the GameCube's yCbCr422 rendering, but there is still some roughness, particularly when red, green, or blue colors are right next to each other. I've tested using yCbCr422 as output, and my TV does better scaling of it than GCVideo does. However, my monitors do not scale 4:2:2 very well, and only accept RGB full over DVI or VGA, so having a better chroma interpolation feature (or a customizable one) would be beneficial for them.

**Comment by ikorb** [comment]
Where do you propose to get the required hardware multipliers from to implement a more complex interpolation formula?

**Comment by GK6475** [comment]
This is a suggestion, I don't know exactly how GCVideo works. I am just asking if improvements to chroma interpolation are possible or not.
