### ISSUE TITLE
audio lag

### ISSUE THREAD

**Issue by Rx-R** [ikorb/gcvideo#11]
Hi, I installed a plutoIIx with 2.3 installed.  I am experiencing audio lag after a certain amount of time of gameplay.  upwards of 2 seconds delay.  I can then turn off enhanced dvi mode then turn it back on and the sound is in sync.  after about 10-20 min of gameplay the lag slowly creeps back again.  Is there something I can check or fix with my install?  I verified it is not the gamecube as when I run audio out of the analog port it is fine.  thanks for your help and your work.

**Comment by ikorb** [comment]
The Gamecube has a slightly non-standard audio sample rate. GCVideo-DVI passes it to the display as-is, any audio lag you encounter comes from the display side. There isn't enough space left in the FPGA to properly resample the audio and just dropping/inserting samples creates an audible distortion.

Your install should be ok. As far as I know the slightly-off sample rate should still (barely) be within tolerances, but it seems you have a device that just doesn't like it.

**Comment by Rx-R** [comment]
thanks for the explanation
