### ISSUE TITLE
OSD doesn't show with Wavebird controller

### ISSUE THREAD

**Issue by vguttmann** [ikorb/gcvideo#111]
I installed an AVE-HDMI in my Wii, and to bring up the OSD, you'd hook up a GC controller to port 1 and press L+R+X+Y.

However, despite all the buttons working, this does not work at all for me.

I'm not sure if this is a limitation on the controller side, or what's going on here, but I thought I'd let you know.

**Comment by ikorb** [comment]
Does a Wavebird not have the "click" when fully pressing L/R?

**Comment by drandreas** [comment]
It work's with my Wavebird but I have to open a manu that supports the GC-Controller e.g. Homebrew Channel.

**Comment by vguttmann** [comment]
Yes, it does have the click, and also yes, I did have to open the homebrew channel.

It works now, thanks!
