### ISSUE TITLE
Add a mechanism to configure remotes for external adapters without an IR button

### ISSUE THREAD

**Issue by vaguerant** [ikorb/gcvideo#121]
Apparently, some manufacturers of external GCVideo adapters don't include an infra-red button on the adapter, which makes configuring an IR remote close to impossible. The example I've been made aware of are the [Bitfunx HDMI Adapter for GameCube](https://www.bitfunx.com/product/bitfunx-hdmi-line-doubler-adapter-gc2hdmi-for-nintendo-gamecube-ngc-digital-to-hdmi/).

An owner of this device described performing a firmware update and the settings being wiped which meant the remote no longer functioned. They then had to disassemble the (glued) adapter casing and short the contacts on the board which would otherwise correspond to an IR button in order to configure their remote again.

The merits of catering to this situation rather than encouraging manufacturers to design their adapters properly can be debated, but for end-users, especially those without the knowledge of how to disassemble a glued case or find and short the correct pins on the board (which is probably a high proportion of users buying cheaper and perhaps less complete GCVideo adapters), that's a bad time.

This means some mechanism to reconfigure an IR remote without a button would be desirable. Below, I'll propose one possible solution; if you have other ideas, feel free to ignore the next two paragraphs.

---

The solution I see would be to have the GCVideo firmware look for some specific (and difficult to reproduce accidentally) video signal coming from the (homebrew-capable) GameCube to indicate that the GCVideo should enter the IR config mode. I have no idea how much of a concern either performance or signal collisions are; if it makes sense to you, maybe it should just run at all times, but I would propose that it makes sense to run this check only on initial start-up of external adapters.

Thus, the IR config process for users who have an external adapter with no (functional) IR button would be to launch a future "GCVideo IR Config Trigger" homebrew app, which displays the designated image, then have the user unplug and re-insert the GCVideo while the app is running (it would make sense for a notice telling a user to do this to be part of the required signal so that they know when it's time to do so). That way, when the GCVideo boots up and performs its IR config signal check, it will encounter the IR config signal and enter config mode.

---

If you do end up going ahead with some alternative IR config trigger, it would presumably only need to run on external adapters, since internal installations can (always?) access the menu using controller input, so any possible degradation in performance (e.g. delay in startup due to looking for IR config signal) would only affect the users most likely to be affected by the issue and would likely be considered an acceptable compromise. If not, the IR config check could be optional--perhaps defaulted to on, since this feature most benefits people who won't have the opportunity to turn it on manually.

**Comment by ikorb** [comment]
Working around broken vendor hardware would just encourage more vendors to ship broken hardware, so I refuse to do it. The button is also essential to trigger the rescue mode in case the main flash is corrupted.

The proper way to fix this is to complain to vendors of broken hardware and asking for a full refund - they intentionally sold crippled hardware after all without disclosing this to the buyer.
