### ISSUE TITLE
Dolby Pro Logic II issue

### ISSUE THREAD

**Issue by TeMouRen** [ikorb/gcvideo#122]
Is using an HDMI splitter to separate the spdif signal the same as using the spdif signal that comes with gcvideo? (Using Google Translate)
I am surprised that GameCube can output 5.1 surround sound.But my bitfunx doesn't have spdif output point.So can I connect an external HDMI splitter to obtain spdif signal？

**Comment by ikorb** [comment]
Yes, the audio data on SPDIF and HDMI are identical - unless you enable the sample rate hack option, but that is not recommended anyway.

The Gamecube cannot output what is nowadays usually called "5.1 surround sound", it only supports two audio channels. Some games however use Dolby Prologic encoding to enable surround sound over these two channels, which even works with the original analog output.

**Comment by TeMouRen** [comment]
Understood it.Thanks for your reply!!!
