### ISSUE TITLE
How can I switch GCvideo lite 's output from 480i to 480p?

### ISSUE THREAD

**Issue by hualazimo7** [ikorb/gcvideo#126]
Checking the readme document, I'd like to ues 480i on my  sony 1410  monitor, so I just left out the pin1 from gamecube, the cable detect pin , and then the output become 480i . However when I connected that pin 1 to cube's pin1 ,the output was also 480i. It didn't suggest me "if you want switch the  output mode"  when I enter the game "Star FOX". 
When connected, the voltage at pin1 was 3.3V indeed. 
I don't understood the problem, at the very very begin, 480P was successful shown.

**Comment by ikorb** [comment]
GCVideo Lite just outputs whatever the game is using, so just switch the game to progressive mode.

**Comment by hualazimo7** [comment]
What weird is after I leftout the pin1 and connected again, It didn't suggest me "if you want switch the progressive mode" when I enter the game "Star FOX".  But at the very begin It did. 

when tested on 1410 I left out pin 1(cause 1410 only support 480i), and then I connected for test on a model tv supported component input, it happened

**Comment by ikorb** [comment]
That's not weird, that is just the game remembering that you said "no" before and not asking again to stop bothering you.

**Comment by hualazimo7** [comment]
@ikorb Sorry for bothering you again, as you said, I connected the pin1 to the cube and set the  video output of swiss at 480i in case the picture corrupted at RGB mode.  At RGB mode, the GBI got black screen no matter what setting it was.
!
#
While under the component mode,  everything was ok , no matter the Swiss set at 480i or 480p.


Is that the issue discribed at the readme.md? 

If so ,  I think I should add a switch in that line.  T.T
