### ISSUE TITLE
Unable to update gcdual past 3.0e

### ISSUE THREAD

**Issue by mesterholm** [ikorb/gcvideo#127]
Hello!

I had a gcdual with 3.0d flashed to it and was able to upgrade to dan's v3.0e but I'm unable to upgrad to v3.1 using any of the available .dol images either from this github or dan's versions. I've attached what shows on the screen during my attempts to upgrade. Any thoughts? Thanks in advance!
![gcvideo-upgrade](https://github.com/ikorb/gcvideo/assets/14977801/0a3fd1de-ea79-4376-94ec-01d173740bdb)

**Comment by Arrghus8** [comment]
Did you resolve this issue? If so, which .dol file did you use?

Edit: For anyone else, my mistake was grabbing the wrong updater from Dan. I didn't notice that there were two versions of his modified firmware.

**Comment by mesterholm** [comment]
Hi Arrghus,
This was the same problem I had, I was trying to use the GCHD_MK2 .dol files and the one that ended up working was one of the GCDual_ADV7125 .dols.
