### ISSUE TITLE
Bitfunx no option to update?

### ISSUE THREAD

**Issue by Obleon** [ikorb/gcvideo#130]
Did Bitfunx remove the option to update?

The about section only shows the copyright text but no update button.

![20240418_013259](https://github.com/ikorb/gcvideo/assets/167376957/b0ff9eb7-1edb-4ce7-810f-904327153256)
![pro-kJ4sWrG3](https://github.com/ikorb/gcvideo/assets/167376957/3b82ae6e-9465-44cb-b39c-f09f60be1c95)
![pro-wJ0HO4Dp](https://github.com/ikorb/gcvideo/assets/167376957/436d97ba-78e7-4499-af31-fa0498fea4aa)

**Comment by ikorb** [comment]
Based on your screenshot it looks like they changed something. If the device has an IR config hardware button you could try to hold that down while powering on the Cube to force-start the flasher instead of the regular firmware - if it exists and they didn't mess with that too.

But you'll have to direct complaints about that to them, I can only help with what is in this repository.

**Comment by Obleon** [comment]
Thanks for the great software!
I own a carby and updated the 2.4 with some JTAG to 3.1 some time ago.

Didn't expect Bitfunx to change the software so you can't update with a .dol there also is no ir config button.

I bought this one for a second setup because the website said it could be updated multiple ways with a usb cable but there is no update software or with a .dol even though there is an official video on the website how to do it but they locked that.
Also I think the device is glued shut? So updating with JTAG might also be a no go.

I send a message to bitfunx Before I made this post. I'll let you know if they by some miracle can fix this problem they created on purpose.

**Comment by Obleon** [comment]
The button/ir switch is missing and shorting the contacts brings up the remote program menu even on power on of and on again.

So I guess they did change something?

Also tried xilinx jtag but unless they changed the order of the pins vs the carby I'm not getting the flash button in the impact software

The image with the flash is from the carby and the other one with flash missing and unknown bypass is the Bitfunx.
