### ISSUE TITLE
Feature request: HD Video modes

### ISSUE THREAD

**Issue by TriVoxel** [ikorb/gcvideo#131]
Is it possible to force the console to natively render games at 720p or 1080p? I know it sounds crazy but, I think if it were possible, even with select titles, it would be incredible!

**Comment by ikorb** [comment]
I don't think so and even if it were possible, it would need to be done in software on the console, so it is out of scope for GCVideo.

But it wouldn't really help as the FPGA used by GCVideo is not capable of running at the clock speeds needed to generate a 720p60 DVI signal.
