### ISSUE TITLE
Feature request: Scale to a standard resolutions for better HDTV compatibility

### ISSUE THREAD

**Issue by TriVoxel** [ikorb/gcvideo#132]
I've noticed a lot of inconsistency when trying to play on modern TVs with my Pluto II. Some TVs have black borders, some don't, some stretch the image, other's display as 4:3 and need to be stretched manually, some straight up don't support the output resolution...

How feasable is it to take the internal resolution and interpolate it to a 1280x720, 1366x768, or even a 1920x1080 image? Possibly with filtering options??! That would be a heck of a lot easier to run on modern TVs, and we could apply 16:9 correction for 4:3 games in the integrated menu instead of letting the TV decide what to do with it. I love GC Video, but just wish the TV compatibility could be improved like this...

I'd be happy if this even required a really lightweight upscaling method like nearest neighbor due to memory issues. Of course, I think this feature should be optional, and native resolution output should remain an option but, I'd love to have this ability somehow if at all possible.

**Comment by ikorb** [comment]
It is completely infeasible: The FPGA cannot generate signals fast enough for a 1280x720@60Hz DVI signal

**Comment by TriVoxel** [comment]
@ikorb Sorry to bother you and continue this discussion but, is it possible a more powerful FPGA device could do such a thing? Or perhaps, even something like a Raspberry Pi could process the video instead?

I know it would essentially require software emulation of the video conversion but, it could yield some cool results? IDK, just trying to think outside the box here, shows how much I really don’t know about these things, haha!

Perhaps a combination of the current FPGA could be coupled with an ARM or RISCV processor to handle the upscaling? I don’t think it would be entirely unfeasible for a manufacturer like the Pluto II’s to make a revised design utilizing a low budget modern processor that has hardware video processing features that can process the HDMI output of the current design. IDK, just thinking out loud here.
