### ISSUE TITLE
OLED65B19LA no signal / blank sceen / black screen

### ISSUE THREAD

**Issue by popy2k14** [ikorb/gcvideo#134]
Dear Community.

First, thx a lot for this amazing project, so we can use our GC/Wii's with a more beautiful picture on modern TV's :-)

I have installed an WiiHDMI v0.4 (with newest GCVideo v3.1) into my RVL-CPU-60 Wii.
It's working without any issue on an 6 year old Philips TV.
Also audio and all video modes tested with different games and it's just works.

When i connect it to my main TV LG OLED65B19LA (in the living room, which is ~3 years old),
it does'nt pick up the HDMI signal or the audio and HDMI Input is grayed out in the menu.
TV just shows no signal. Every other device i have thrown at my LG was working (Shield, WiiU, PC, ...)

PS.: The Wii is set to HDTV 480p

What i have tried to fix the issue without success:

- Use different HDMI cable (and the one which is working on the Philips)
- Use different HDMI input on the LG
- Use Denon AVR-x2400h in between
- Tried Enhanced DVI off/on and other advanced settings
- Masure HDMI 5V & DDC -> OK
- Check/Update OLED TV Firmware to 03.40.82

It's was always the same, it did'nt pick up the HDMI signal and HDMI Input is grayed out in the menu.

**I had an old 1080p FullHD HDMI muxer (3 in & 1 out) laying around and yeah, that fixed the issue completely!!!!**
I think every cheap HDMI splitter will solve such issues, because it does the handshake with the TV correctly.

So why i am posting this when it's fixed.
Maybe somone else is having similar issues and this could help.

Also maybe there are some handshake issues in the current GCVideo to the LG OLED.

**Comment by zardam** [comment]
I think I had the same issue. I solved it by replacing this resistor by a solder bridge:
![image](https://github.com/user-attachments/assets/98aac939-53e6-4f8f-badb-05890f44cf2a)
The resistor is placed between the +5V of the Wii and the +5V of the HDMI port. On my board, it was 1kOhm, way too high to power anything connected to the HDMI port.

**Comment by popy2k14** [comment]
@zardam thx a lot for pointing this out.
Now found time to look at it and guess what?

Yeah, my HDMI board had a 10k!! (way to high) pull up to 5V.
Back then i measured the 5V on the HDMI and it was ok, but just unconnected (unloaded) on the other side.

After replacing the 10k resistor to an 0 Ohm bridge, all is working as expected and the issue is solved!
Thx a lot!!!!!!
Sadly i did not had any resistors with low value and the correct size laying around.
I hope the Wii has an current limiter on the USB ports, so that would not be an issue in the future.
