### ISSUE TITLE
Get the gcvideo-dvi-p2xh-gc-2.3.bit

### ISSUE THREAD

**Issue by Hawkeye92** [ikorb/gcvideo#15]
Hi, firstly congratulation for your great job

I receive my Pluto board but I cannot get it to work.
All my connections are goods, double checked.
When I turn on the console, one LED blink but the another LED still ON without any blinking, so in your readme you say that the board is probably not programmed.
Maybe my board isn't programmed, so I would like to get the file "gcvideo-dvi-p2xh-gc-2.3.bit" but I can't find it, there is no bin subdirectory.
Can you upload it ?

**Comment by ikorb** [comment]
https://github.com/ikorb/gcvideo/releases
