### ISSUE TITLE
DOL-101

### ISSUE THREAD

**Issue by ManuPerezBelmonte** [ikorb/gcvideo#2]
Sorry for contacting you that way, I didn't another way how to contact you. 
I've been checking everything in your repo and first of all, it's genius. However I saw that it's not possible to use a DOL-101 version, did you find something new regarding this model? or it was impossible for you to try it? As the boards come already programmed I don't know if I should still need to program something or even if there is going to be a way to use it on the DOL-101.

**Comment by ikorb** [comment]
Sorry for hiding the 98 copies of my email address in the repository so well.

The DOL-101 is missing the external digital video port, but I suspect that all required signals are still present on the board. You would need to wire the FPGA board directly to the AV encoder chip and find a different source for the 54MHz clock signal somewhere on the board - I heard that it exists, but I don't know where.
