### ISSUE TITLE
Chroma shift still exists on Wii

### ISSUE THREAD

**Issue by Xaranar** [ikorb/gcvideo#20]
Have installed the latest release of the Wii version, and there is still a chroma shift to the left of objects on screen.  It's most obvious on the Wii's dashboard, the blue circles encapsulating the Wii and Messages buttons show a ghost image slightly to their left.

**Comment by ikorb** [comment]
The fix in 2.4b is for a different chroma shift.

I'm still not sure if the Wii chroma shift is real or is just a consequence of 4:2:2 processing by the console. Analysis based on captures from the 240p test suite indicates that the output generated from the console is identical for Gamecube and Wii, so in theory any shift should be observable on both consoles (or both modes on Wii).

**Comment by Xaranar** [comment]
I've done some testing on it myself, and it is viewable in GameCube mode on the Wii, but not to the same degree as I shall explain.  Running GameCube games via Nintendont enables you to change the horizontal scaling as well as the positioning, all the way up to a full 720 pixels across for a perfect 4:3 ratio.  This does cause the weird chroma shift, only if those values aren't set in multiples of 4.  I've tried shifting the screen around on the Wii, and it makes no difference to anything in Wii mode.

**Comment by ikorb** [comment]
Oh, I forgot this issue was still open. It should be fixed in 2.4d.
