### ISSUE TITLE
FPGAconf does not support .bin files.

### ISSUE THREAD

**Issue by sbagneris** [ikorb/gcvideo#24]
FPGAconf explicitly wants .bit files to flash firmware onto a Pluto II board. This is no longer provided with the 3.0 release.

It is possible to rename the .bin file file to .bit file and FPGAconf will happily (foolishly?) flash the file onto the board but when booting the picture is now black and white and the following message is displayed:

"!!! Updater hardware ID is invalid !!!"
"--> YOU must choose the correct ID <--"
"Main firmware is missing"

A rotating cursor is displayed bellow and when pressing the z-button a hex dump of the ROM is displayed that can be navigated up and down the memory addresses.

Long live GCVideo!

**Comment by ikorb** [comment]
It seems that FPGAconf is trying to remove a header from the "bitstream" file to get to the actual contents and the part it removed it small enough that the FPGA still boots. However, the flasher that starts first thinks that the main firmware is bad and starts its recovery mode instead of booting the main firmware.

Good thing I added that memory hex viewer for diagnosing problems like this. =) Run it, hit the X button (should jump to address 30000), take a picture, hit left on the D-Pad once (shoudl jump to 2ff80) and take another picture. With a bit of luck that should be enough to figure out how to build a pseudo .bit file that can be flashed with FPGAconf.

**Comment by sbagneris** [comment]
You bet! 

Note to anyone else reading that the Pluto board is not bricked when doing this. One can easily revert to 2.4d without harm.

![E7F1BE24-A7A8-448E-8FF3-33AD21C6D052](https://user-images.githubusercontent.com/653039/72225779-32845800-353e-11ea-89ec-68557736080e.jpeg)
![4CA5CFD2-6715-4F2C-B56D-679AC416A66D](https://user-images.githubusercontent.com/653039/72225780-32845800-353e-11ea-9d24-a7957898e04d.jpeg)

**Comment by ikorb** [comment]
Thanks!

Unfortunately FPGAconf did something completely against my expectations - instead of dropping the (nonexistant) .bit header, it added something, which shifts everything backwards instead of forwards. Could you take another screenshot from address 0?

**Comment by sbagneris** [comment]
No problem.

I included the first two pages.

![D2837355-8F17-4846-A01D-2F14BFE8FD02](https://user-images.githubusercontent.com/653039/72225869-42506c00-353f-11ea-8560-078c7b4095ab.jpeg)
![278D6727-4768-4BD7-A3BB-F880426E017D](https://user-images.githubusercontent.com/653039/72225870-42506c00-353f-11ea-85bb-4dea3b91c717.jpeg)

**Comment by ikorb** [comment]
Thanks. The file below might work with FPGAconf. If it doesn't, I'll probably need a few days to dig out my own hardware to figure out a workaround.

[gcvideo-dvi-3.0-p2xhgc-fpgaconf.zip](https://github.com/ikorb/gcvideo/files/4051502/gcvideo-dvi-3.0-p2xhgc-fpgaconf.zip)

**Comment by sbagneris** [comment]
Success!

![34BDC2A3-B648-47E3-8615-BC0D8576A88A](https://user-images.githubusercontent.com/653039/72226129-71b4a800-3542-11ea-9fd9-5daf9e32e5c7.jpeg)

**Comment by ikorb** [comment]
Nice! Thanks for helping figure this out, I'll add a link to the release notes.

P2XH Wii fake bitstream in case someone actually uses it:
[gcvideo-dvi-3.0-p2xhwii-fpgaconf.zip](https://github.com/ikorb/gcvideo/files/4051549/gcvideo-dvi-3.0-p2xhwii-fpgaconf.zip)

**Comment by sbagneris** [comment]
Thank you *very much*. I would have given you two thumbs up but I can’t quite levitate my camera yet. Most thing at first glance seems to function just fine. I’m excited for the built in firmware upgrade.

**Comment by ikorb** [comment]
Actually the system is resilient enought that you could have used the 3.0 updater to install a working main firmware by manually selecting the correct board ID - but since you appeared to be a willing victim, I preferred to work out the problem so others can avoid it completely.

**Comment by sbagneris** [comment]
By all means!

**Comment by Tazberry** [comment]
@sbagneris what are you using to update ur pluto?

**Comment by sbagneris** [comment]
I'm using the basic TXDI header from KNJN along with FPGAconf software that should have come along your purchase of the Pluto board. A judicious search online should net you a downloadable package for FPGAconf if you have lost the files. (it is not available on the KNJN website for some reason) or email KNJN for a link.

**Comment by Tazberry** [comment]
@sbagneris Is it possible I can get a link to all this. Doing this for the first time.

**Comment by GizmoTheGreen** [comment]
what are you using to connect to the TXDI header if you don't mind me asking? I've got a Sparkfun FTDI basic. put the TX in invert and been emailing KNJN. checking voltages on the TX RX lines etc but can't for the love of me program the thing. 
it just times out! (still on 2.4c)

**Comment by sbagneris** [comment]
I use a bog standard USB to serial adapter and I plug the TXDI header right into it.
This looks pretty identical to what I have:
https://www.amazon.com/Tripp-Lite-Keyspan-High-Speed-USA-19HS/dp/B0000VYJRY/ref=sr_1_4?crid=30ZQBZIKGFGJS&keywords=usb+to+serial+adapter&qid=1579027516&sprefix=usb+to+serial%2Caps%2C180&sr=8-4

The specific TXDI header I use is the plain jane one without the RS232 chip built in ($6.95)
https://www.knjn.com/ShopAdapterBoardsTXDI.html

**Comment by GizmoTheGreen** [comment]
> I use a bog standard USB to serial adapter and I plug the TXDI header right into it.
> This looks pretty identical to what I have:
> https://www.amazon.com/dp/B0000VYJRY/ref=cm_sw_em_r_mt_dp_U_C1GhEb3Q1G029
> 
> The specific TXDI header I use is the plain jane one without the RS232 chip built in ($6.95)
> https://www.knjn.com/ShopAdapterBoardsTXDI.html
> 
> Additionally, the following may be of further help:
> https://www.knjn.com/docs/Re-programing%20Pluto-IIx%20HDMI%20with%20the%20latest%20gcvideo%20release.pdf

thanks for your input. I've read that PDF and referenced it when I hooked up the FTDI.
as I mentioned I've been emailing KNJN and they say it looks correct but have no idea why I can't program the board.

I should probably make a new "issue" to try and get help with this here but for now I'll just share the pictures.

![image](https://user-images.githubusercontent.com/1146558/72383275-71bbd000-371b-11ea-8638-b93e771a2c4f.png)
![image](https://user-images.githubusercontent.com/1146558/72383315-7f715580-371b-11ea-8926-d263c276a935.png)
