### ISSUE TITLE
3.0 does not appear to save settings

### ISSUE THREAD

**Issue by sbagneris** [ikorb/gcvideo#25]
I'm likely doing something wrong but it appears setting changes do not survive a power cycle of the console.

This happens of course despite explicitly calling "save configuration" in the menu.

The specific setting I'm attempting to make stick is the "Enhanced DVI" mode so that digital audio streams through the "HDMI" instead of having to use the analog out.

Not a big deal.

**Comment by ikorb** [comment]
Actually it is a big deal because it could erase parts of the bitstream from the flash... Fixed in 3.0a.

**Comment by sbagneris** [comment]
oooooh boy... and here I was mashing that "save configuration" button... Ignorance sometimes *isn't* bliss!
Thanks again for the lightning fixes!

GCVideo still kicking butts and taking names.

**Comment by sbagneris** [comment]
Ok tried this updater thing! It works beautifully and all issues are confirmed fixed.

Launch straight from SWISS!
![485475C8-A689-4960-9810-27DB98AD14B1](https://user-images.githubusercontent.com/653039/72310011-7312cd00-3635-11ea-8abb-7fdb8cda2877.jpeg)

![9E8147D7-C6AA-4FCC-B1BC-BADFB94F4E8D](https://user-images.githubusercontent.com/653039/72310012-7312cd00-3635-11ea-895b-fb2b5014fda2.jpeg)

On reboot presented with pretty clear instructions.
![C21C4E6D-D769-47B6-910D-58FBE2F5091A](https://user-images.githubusercontent.com/653039/72310013-7312cd00-3635-11ea-811e-c06d9f5d338f.jpeg)

Time to flash!
![347F55C0-11A9-4F34-843E-47BBD686E925](https://user-images.githubusercontent.com/653039/72310014-7312cd00-3635-11ea-906b-85fd0d06d536.jpeg)

Here we go...
![5487F88A-B866-45BD-B008-3EC7943194F6](https://user-images.githubusercontent.com/653039/72310015-7312cd00-3635-11ea-8d1f-69908e1b1ebd.jpeg)

Flashing...
![4A316701-A9C4-47CE-8B55-B7F002E4FCE4](https://user-images.githubusercontent.com/653039/72310016-73ab6380-3635-11ea-8841-6d83bbb20a4f.jpeg)

Auto reboot is nice...
![B1323D59-61C8-44CC-95A7-3A2BBCC0FCDF](https://user-images.githubusercontent.com/653039/72310017-73ab6380-3635-11ea-8ec4-b5d62dd79446.jpeg)

I suppose you see this again if you want to flash it again on reboot?
![3F3EE395-3554-4EC0-B1C1-E3D1D1A510EA](https://user-images.githubusercontent.com/653039/72310018-73ab6380-3635-11ea-8bf4-1a06d619a168.jpeg)

Great success!
![41E2EBB5-3E6C-4755-9764-738C95FCF427](https://user-images.githubusercontent.com/653039/72310019-73ab6380-3635-11ea-93e9-2ef1b3dd26fd.jpeg)

**Comment by ikorb** [comment]
There is no feedback path from GCVideo back to the Gamecube that works on all hardware variations, so the updater doesn't know that it can exit and you get the noise screen back after GCVideo reboots.

**Comment by dropdennisdead** [comment]
Hi, i have the same Problem as @sbagneris. When i start the gamecube i have no sound. when i turn on the enhanced dvi mode in the settings i get a sound but when i restart the console the settings are not saved. Do you have a version of the GC Video 3.1 where the enhanced dvi mode is always on? Thanks in advance!

Greetings
Dennis

**Comment by ikorb** [comment]
The "Save does not save" bug has been fixed a few years ago already. Since you did not mention anything about trying to save settings, I'm going to assume that you forgot to do so and advise you to try that.
