### ISSUE TITLE
Black screen when returning to Wii menu

### ISSUE THREAD

**Issue by Xaranar** [ikorb/gcvideo#27]
Thanks for all your work so far, it has been so helpful, and version 3.0b is now working in full colour.  However, although booting into USB loader GX works fine, every time I try to return to the stock Wii menu it just goes completely black and the screen seems to lose sync.

**Comment by ikorb** [comment]
Try this:
- boot into USB loader GX
- start the GCVideo firmware updater (About->Update firmware only, not the updater.dol on the Wii)
- return to the stock Wii menu

Does the the signal drop out or do you get a visible Wii menu overlaid by the firmware updater's prompt?

(this test narrows down the cause)

**Comment by Xaranar** [comment]
I am able to see the stock Wii menu this way, it is overlaid by the update being requested but the screen is in black and white.

**Comment by ikorb** [comment]
Thanks, so thankfully it's not related to the Wii fixes in 3.0b and it's most likely a software problem.

It looks like I can reproduce it here, fix hopefully coming soon.

**Comment by Xaranar** [comment]
Awesome, thank you!

**Comment by ikorb** [comment]
Could you try this one please?

[updater-TEST-wii.zip](https://github.com/ikorb/gcvideo/files/4087777/updater-TEST-wii.zip)

**Comment by Xaranar** [comment]
Tested, that one works perfectly.
