### ISSUE TITLE
Add GCPlug hardware target

### ISSUE THREAD

**Issue by Shiftone** [ikorb/gcvideo#28]
Just popping this here so it doesn't fall off the radar. I know Dan was going to get the constraints file over to you for the GCPlug.

**Comment by ikorb** [comment]
Would you be able and willing to test a GCPlug build (since I don't have one)?

**Comment by Shiftone** [comment]
Yes and yes. I have a unit and programmer on hand.

**Comment by ikorb** [comment]
Great! A test build is attached.

A rough guide to testing everything:
* Does it display a picture at all?
* Are the colors correct or are any of the three channels (R/G/B) inverted?
* Hold down the button to bring up the IR config menu and try to set up a remote
* Turn on enhanced DVI mode in the menu and check if audio works on both channels (this will likely fail if one of the three color channels is inverted)
* Store settings
* Try to install a firmware update (run the included .dol file and use About->Firmware update to start the flasher)
* If the flasher does not detect any available update, hit right on the IR remote to enter diagnostics mode. If everything is fine, it should say that it has detected the test data and show "None" for all three tests.

**Comment by Shiftone** [comment]
- Does it display a picture at all?
Yes
- Are the colors correct or are any of the three channels (R/G/B) inverted?
No
- Hold down the button to bring up the IR config menu and try to set up a remote
Working
- Turn on enhanced DVI mode in the menu and check if audio works on both channels (this will likely fail if one of the three color channels is inverted)
Working
- Store settings
Working
- Try to install a firmware update (run the included .dol file and use About->Firmware update to start the flasher)
Shows Plug1 as current and update version. Completes upgrade process, restarts and works
- If the flasher does not detect any available update, hit right on the IR remote to enter diagnostics mode. If everything is fine, it should say that it has detected the test data and show "None" for all three tests.
N/A

**Comment by ikorb** [comment]
Thanks, looks perfect =) Will officially land in the next release, probably this weekend.

**Comment by Shiftone** [comment]
perfect - glad I could help and thank you for your work on this project
