### ISSUE TITLE
Unable to access OSD

### ISSUE THREAD

**Issue by bsbarham** [ikorb/gcvideo#3]
I purchased a Pluto-IIx XC3S200 HDMI board pre flashed with gcvideo 2.2. I am displaying video just fine, but the designated button combo is not bringing up the OSD. I have checked and re-checked the controller solder point and everything looks good. When contacting the supplier they are suggesting an issue with gcvideo 2.2 (see forum post below). Has something changed with the install? I am also including a picture of the controller solder point for verification. I apologize for the quality. 

Thank you,

KNJN forum post: http://www.knjn.com/phpbb/viewforum.php?f=2
Youtube thread with others with same issue: https://www.youtube.com/watch?v=5Hw_XQdugI4

![img_3319](https://cloud.githubusercontent.com/assets/8399627/18672011/4882ec68-7f14-11e6-9754-c82abdc5db34.jpg)

**Comment by ikorb** [comment]
As far as I can tell yet, it is an issue where the OSD CPU crashes during initialisation and it does not appear with every install - e.g. my development setup was unaffected, so I did not catch it before release. I finally managed to reproduce it yesterday and I'm working on a fix.

**Comment by ikorb** [comment]
Found it, should be fixed in version 2.3
