### ISSUE TITLE
WiiDual Analog RGB Corruption

### ISSUE THREAD

**Issue by PolydactylCat** [ikorb/gcvideo#30]
I flashed the 3.0b firmware you posted for Wii and everything seems to be working alright except for RGB analog output.  YPbPr is fine and HDMI output works fine.  Going back to Dan's 2.4c.2 fixed the problem.  I'm using a RetroAccess Wii SCART cable with sync carried over data pin 15 running through an OSSC.
![RGB](https://user-images.githubusercontent.com/60170988/72873289-72c1a400-3cbd-11ea-87dc-9358185693e2.jpg)

**Comment by ikorb** [comment]
Oh wow, that looks interesting. Could you try the attached firmware version? It will have swapped color channels in RGB mode, but the interesting part to me is if the image still has these jagged stripes across it.


[updater-wii-TRGB-dual-wii.zip](https://github.com/ikorb/gcvideo/files/4100286/updater-wii-TRGB-dual-wii.zip)
[gcvideo-TRGB-dual-wii.zip](https://github.com/ikorb/gcvideo/files/4100289/gcvideo-TRGB-dual-wii.zip)

**Comment by PolydactylCat** [comment]
It looks pretty much the same.  When I switch over to RGsB, it seems to decrease the double image ghosting, but the colors are still wrong.  Looking at a mismatched YPbPr with the OSSC on RGBS- it looks like the jagged lines are just exaggerations of the color banding in the homebrew launcher background.
On a side note- I'm also having trouble with the .dol updater.  It holds on the spinning asterix, but doesn't recognize the new FW.  Once when I ran the program, it flashed text at the bottom of the screen too fast to read, and resynched the video every 15 seconds or so, but every other time it just hanged.
Could this just be a manifestation of my subpar soldering causing minor graphical hiccups amplified by the new FW?
![RGB_2](https://user-images.githubusercontent.com/60170988/72945901-4b191d00-3d4b-11ea-9751-a3d6cb8bd0b7.jpg)
![RGsB_2](https://user-images.githubusercontent.com/60170988/72945904-4c4a4a00-3d4b-11ea-9a1f-a68d17af37ca.jpg)
![YPbPr](https://user-images.githubusercontent.com/60170988/72946011-9c291100-3d4b-11ea-9e55-5114790d8def.jpg)

**Comment by ikorb** [comment]
The updater.dol way of updating the firmware needs all bits of video data working correctly, so if you have a dodgy connection somewhere that would explain why the update is not recognized. I don't think it would create RGB-only video corruption though.

Thanks for the pictures, I need to run a few tests before I can suggest a next step.

**Comment by PolydactylCat** [comment]
I hate to to pile on, but I'm getting similar findings on the GCDual side.  Analog RGB has a red film over it that doesn't show up too great in pics and the firmware updater won't work.  As with the Wii, YPbPr and HDMI RGB work great.  Also the update .dol is invalid from a GCLoader, but it will run from a Gecko or SP2SD2.
![GC_RGB](https://user-images.githubusercontent.com/60170988/72947859-74d54280-3d51-11ea-9548-10cabcc93520.jpg)
![GC_YPbPr](https://user-images.githubusercontent.com/60170988/72947861-769f0600-3d51-11ea-9752-a63b73ac4877.jpg)

**Comment by PolydactylCat** [comment]
Okay, I had the "Digital color format" set wrong, don't mind me.  The GC updater still won't acknowledge the update file though.  Thank you kindly for all the time and work you put into the community.

**Comment by ikorb** [comment]
I think the HBC banding in your picture looks stronger (wider bands) than the banding I see in my own HBC install, which could point to a missing/shorted/stuck video data bit from your console - that would also explain why the updater can't find an update or acts erratically.

I'm less sure that this can explain the RGB-only banding on the analog output though. This could be an issue on your WiiDual board or an error in the pin assignments I used. This can probably be cleared up when citrus3000psi is back as he said he'd snd me the data needed to build firmware for all of his PCB variants.

On the positive side, your problem has inspired me to add a diagnostic mode to the firmware flasher which tries to detect if all video data lines are are connected correctly. It should be in 3.0d or 3.1 as I want to release 3.0c with another important fix first.

**Comment by PolydactylCat** [comment]
Sounds good.  That would be an awesome feature for hobbyists who can have a successful-appearing install that isn't necessarily a successful install.  I've reinspected my install and touched up some of the solder points but it didn't seem to fix the analog output, and the installers won't work on GCDual or WiiDual.  Thanks so much for all of your work to create and improve this project.  Take your time to implement a fix and let me know of there's anything you I can test in the meantime while my Wii's open.

________________________________

**Comment by ikorb** [comment]
There is one more thing you could do to allow a bit more insight into the analog problem: Run the [240p test suite](https://sourceforge.net/projects/testsuite240p/) on your Wii with a 3.0 firmware and take a picture of the [color bars pattern](http://junkerhq.net/xrgb/index.php?title=240p_test_suite#Color_Bars) on the analog output in both RGB and YPbPr mode.

**Comment by PolydactylCat** [comment]
I hadn't tried before, but it turns out I can't install the 3.0a firmware due to the "Booting main firmware failed" error.  These were taken on 3.0b.
Wii (RGB)  ->  OSSC (RGBS)   ->  TV
![RGB to RGBS](https://user-images.githubusercontent.com/60170988/73126987-d54dc500-3f87-11ea-941a-f4729953bb26.jpg)

Wii (YPbPr)  ->  OSSC (YPbPr)   ->  TV
![YPbPr to YPbPr](https://user-images.githubusercontent.com/60170988/73126995-f0203980-3f87-11ea-919b-e1dafee7677e.jpg)

Wii (YPbPr)  ->  OSSC (RGBS)   ->  TV
![YPbPr to RGBS](https://user-images.githubusercontent.com/60170988/73127008-22319b80-3f88-11ea-9410-e91f8bea1336.jpg)

Wii (HDMI)  ->  Receiver (Reports as RGB 4:4:4)  ->  TV
![HDMI](https://user-images.githubusercontent.com/60170988/73127011-28277c80-3f88-11ea-87f1-b509c3b7cfbb.jpg)

**Comment by Leafeon412** [comment]
Hello, I am running a WiiDual with version 3.0c installed and experiencing the same issue. Using an OSSC with Retro Access RGB scart cable. Let me know if I can provide any help testing firmware.

**Comment by PolydactylCat** [comment]
New builds, new developments.
I manually flashed Dan's 3.0c build for WiiDual1.1.  It cleaned up the RGB corruption, and also is able to recognize his updater.dol file, but it's still doesn't recognize a compatible firmware file when I tried flashing the updater.dol for 3.0d from here.  For the time being, I'll just update the Wii with firmware from his site.

It's still not quite perfect because either the color channels are swapped on analog RGB out or I've messed up a setting.  YPbPr remains solid.
![RGBS](https://user-images.githubusercontent.com/60170988/73700428-88b76780-46b4-11ea-8e70-1de942e26bc9.jpg)
![YPbPr](https://user-images.githubusercontent.com/60170988/73700434-8bb25800-46b4-11ea-9711-d024302a67fa.jpg)

**Comment by PolydactylCat** [comment]
One final addition:  I flashed 3.0d do see what happens and it has the same problems with analog RGB.  Updater.dol doesn't work and gives the following in diagnostic mode:
![firmware_dx](https://user-images.githubusercontent.com/60170988/73711109-da231f00-46d3-11ea-8766-365de609e201.jpg)
I'll leave my Wii open for a few more days in case you want me to run some tests, but it's understandable if you want to let Dan sort out the optimization of your firmware for this hardware. 

Thank you for all the groundwork you've done to create and enhance these projects.

**Comment by Xaranar** [comment]
Far be it from me to assume I know anything about what's wrong, but the fact that in diagnostics mode AData is reported as missing or silent says to me that there is a problem with that connection to the FPGA.

**Comment by ikorb** [comment]
@PolydactylCat: Ok, then it seems that citrus has changed something in his build that is needed to support the hardware and as of now he has not told me what that change is or how to implement in my build. Is't it nice when people take an open source project and make a closed-source variation?

@Xaranar: No, the updater does not output any audio, so AData not showing OK is normal.

**Comment by citrus3000psi** [comment]
@ikorb there is nothing changed in the firmware that is special to support the build.  The Scart cables on the WiiDuals (like the ones from RetroAccess) have the colors swapped so nothing would have to be done in firmware for the colors to appears correct. https://i.imgur.com/nwVKO9r.jpg.  

This is listed in the instructions on the WiiDual installation, http://dansprojects.com/wiidual_install.html

I assume it has something to do with this, GENERICS := SwapRed=\"YES\" SwapGreen=\"YES\" SwapBlue=\"YES\"  But have no investigated any farther.

**Comment by ikorb** [comment]
The three generics just define which TMDS pairs have positive/negative swapped and have no effect on the analog output.

The current version does try to swap the analog colors around when you switch between RGB and YPbPr, but that should only result in a color-swapped picture on the analog output and not such major corruption.

**Comment by citrus3000psi** [comment]
From the last images it looks like it’s just color swapping. No idea what’s causing the corruption posted earlier.

**Comment by PolydactylCat** [comment]
The set image with the color swap was taken with the 3.0c firmware posted on citrus3000psi's website.  The initial set with severe RGB corruption was taken with the 3.0b build from ikorb.

The firmware branches also seem to handle updater.dol differently.  Within citrus' firmware branch it works fine, but when ikorb's 3.0d was installed, diagnostic mode reports a stuck bit on the vData 0 line.  I am unable to jump between firmware branches using updater.dol.  This may or may not be related to the above issue.

**Comment by ikorb** [comment]
The attached version should have a fully-working analog RGB output and it should also not report problems with VData 0 anymore.

(root cause: three incorrect pin assignments in my version)

[gcvideo-WDTEST-dual-wii.zip](https://github.com/ikorb/gcvideo/files/4182934/gcvideo-WDTEST-dual-wii.zip)
[updater-wii-WDTEST-dual-wii.dol.zip](https://github.com/ikorb/gcvideo/files/4182936/updater-wii-WDTEST-dual-wii.dol.zip)

**Comment by PolydactylCat** [comment]
Sir, I believe you have solved this issue!  With this firmware there is no more analog RGB corruption, the colors are all running to the appropriate (though technically incorrect) color channels, and the updater.dol works.  You should be able to close out "Unable to update using 3.0c Wii dol" as well.  Thanks for all your hard work.

Out of curiosity, I wasn't able to get the updater.dol to work from your firmware to citrus' or vice-versa.  Users should plan on picking one branch and sticking with it.

**Comment by ikorb** [comment]
Thanks for testing!
