### ISSUE TITLE
Unable to update using 3.0c Wii dol

### ISSUE THREAD

**Issue by kimbapslice** [ikorb/gcvideo#31]
Hello!
I am trying to update from 3.0b Wii to 3.0c but the updater dol doesn't seem to process correctly, not allowing the prompt to update
![IMG_20200127_222813127](https://user-images.githubusercontent.com/58018661/73233484-b2bcd700-4154-11ea-9ce0-96edb123a141.jpg)

**Comment by kimbapslice** [comment]
GCdual and Carby updated via dol correctly, wii version is being stubborn for some reason. I think by default the menu settings are ignored correct?

**Comment by ikorb** [comment]
My current theory is that you may have a minor wiring problem that does not result in visible video errors, but changes the video data enough that the flasher cannot recognize the update. I'm working on a diagnostic mode that should be able to detect this problem - if you are impatient, I could try to build the current version for you to test, but it's still a software-only implementation and thus not as fast as I would like it to be.

What do you mean by "by default the menu settings are ignored"? If you are referring to the firmware updater on the GCVideo side, it ignores all settings except for IR remote codes.

**Comment by kimbapslice** [comment]
I was wondering if the GCvideo menu specific settings ("Resolution Hack", full or limited color, etc.) would in anyway affect the "update signal". Anyway, I am patient and curious to see if the upcoming diagnostic mode will reveal any wiring issue.

Thank you!

**Comment by ikorb** [comment]
No, I hardcoded basically every aspect of the video signal in the flasher, with an eye towards maximizing compatibility. It even does something that the main firmware can't do, when the Cube generates an interlaced signal it is passed as-is on the analog output (if available) and line-doubled on the digital one. That's also one of the reasons why everything is in black and white, the rewiring trickery used there only works for luma.

**Comment by kimbapslice** [comment]
Hi ikorb,
Also, I normally set the Wii to display in Widescreen and 480p (official Nintendo menu). When displaying the Wii menu or homebrew menu, (in games as well I think), the gcvideo "IN" resolution is shown as 672x960i60 (during homebrew channel menu) "OUT"  720x480p60. Is this behavior correct?

**Comment by kimbapslice** [comment]
![IMG_20200119_173306977](https://user-images.githubusercontent.com/58018661/73364805-3243c680-4279-11ea-99a5-ecb3a0d40766.jpg)

**Comment by kimbapslice** [comment]
Sorry, I am just wondering if it has any relation to different wiidual revisions and such, thus affecting the update procedure.

**Comment by ikorb** [comment]
You have a connection problem or short on video data line 0. It's the pin on the edge marked with "0" in [this image](https://github.com/ikorb/gcvideo/blob/master/HDL/gcvideo_dvi/doc/wii-digitalav.jpg). Fixing this will likely also make the updater work.

**Comment by kimbapslice** [comment]
I tried to reflow the ribbon cable to pin 0 with the same result. I did install the wiidual myself so maybe either the (i bought a used wii) motherboard is bad or I screwed up the wiring somewhere along the way. I will wait for the diagnostic firmware feature to get more details. Thanks ikorb!

**Comment by kimbapslice** [comment]
Hi ikorb,

With all of the trouble with the wiidual versions, I will stay with Dan's releases. Closing this issue.
