### ISSUE TITLE
No signal if HDMI is connected when powering on

### ISSUE THREAD

**Issue by BenoitCaron** [ikorb/gcvideo#33]
Hello,

I finally installed my Pluto IIx board, and it kinda works.

The issue I’m facing is that the Pluto board won’t output a signal if my HDMI cable is plugged in before powering the console on. When the cable is connected upon boot, LED 29 give me a solid light, and I get no signal. If there is no cable upon boot, LEDs 28 and 29 each blink at different speeds, and then connecting the HDMI cable will get me a signal.

Firmware version: 3.0d

Any help would be greatly appreciated!

Regards,
Benoit

**Comment by ikorb** [comment]
I've observed a similar problem on my development board, but only if it is connected to a powered-off TV when turning the Gamecube on. In this situation, something causes the FPGA to not accept the bitstream it is reading from the flash memory.

Do you by any chance use an unpowered HDMI switch that tries to leech power from its inputs?

**Comment by BenoitCaron** [comment]
My current setting is an Onkyo TX-NR737E receiver hooked up to my OLED55C6V LG TV, with the Gamecube being connected to the receiver.
The receiver acts as a hub / splitter, and shouldn't be underpowered. Also, it was of course turned on during my testing.

**Comment by ikorb** [comment]
Is the LED brightness in the failure case the same as during normal operation?

Oh, and since you fixed your other problem by re-routing the 54MHz signal: Does the startup failure still occur or was it also fixed?

**Comment by BenoitCaron** [comment]
The led seems less bright in the failure case. Here is a video of both cases: failure then success.

The other problem is actually not permanently fix and is very much depending on the cable routing - I've had a hard time maintaining a clear signal after moving my console. I'm still waiting on my 3D printed mount, hoping I can find a definitive routing.

So I wouldn't be able to give you a clear answer yet.

**Comment by ikorb** [comment]
Thanks! That looks slightly different than a boot failure on my board and I'm not sure if the FPGA boots far enought that this can be fixed in software.

Could you try the version linked below and check if it changes anything?
[gcvideo-p2test-p2xh-gc.zip](https://github.com/ikorb/gcvideo/files/4272642/gcvideo-p2test-p2xh-gc.zip)

**Comment by BenoitCaron** [comment]
Could you give it to me as a .bit file please?

**Comment by ikorb** [comment]
Sure.

[gcvideo-p2test-p2xh-gc-fpgaconf.zip](https://github.com/ikorb/gcvideo/files/4277687/gcvideo-p2test-p2xh-gc-fpgaconf.zip)

**Comment by BenoitCaron** [comment]
I tried with this version, same as before. I'll try and use it on my work monitor, see if it changes anything.

**Comment by BenoitCaron** [comment]
I noticed [issue #12 ](https://github.com/ikorb/gcvideo/issues/12) was similar to mine, and the issue seemed to be the wiring. Does the fact that I can manage to get a signal by pluging my HDMI in afterwards mean my wiring is correct?

**Comment by ikorb** [comment]
If it works after replugging, your wiring is likely correct, although that does not rule out interference issues as you've seen with the picture dropping out.

There is something you could try: Remove the resistor between VUnreg and DDC+5V. If the board starts up fine without that resistor, but with HDMI connected that would indicate the source of the problem. Please note that you might not get a picture without that resistor even if the LEDs are blinking correctly and you'll probably want to connect that resistor again after the test.

(I wanted to try something similar on my board first, but didn't have time to do so yet)

**Comment by BenoitCaron** [comment]
The LEDs behave the same without the resistor. As expected, no more picture without it.

**Comment by ikorb** [comment]
Thanks for testing, that narrows down things a bit.

I still have one theory that is consistent with the observed behaviour - you seem to have used very thin wires to connect the board to the Gamecube. While this is ok for the data and clock signals, it may be too thin for the power (VUnreg and GND) as the FPGA draws a surprisingly high amount of current when it is active. Would you mind trying to change the wires connected to the GND and VUnreg pins of the Pluto board to a thicker gauge? Alternatively you could use the same wire, but run two strands in parallel for each pin.

(and if that theory turns out to be wrong there are still a few desperate measures that could be tried, but I first need to implement and test them locally)

**Comment by BenoitCaron** [comment]
Alright, then I'll try that tomorrow. I do not have thicker wires, but I do have stranded wire, if that's ok? If not, I'll make sure to run two strands as advised.

**Comment by ikorb** [comment]
If the copper area (or diameter) of the stranded wire is significantly larger than the one of your current wires it should be ok.

**Comment by BenoitCaron** [comment]
Stranded wire did not change the LEDs pattern, nor did having two strands in parallel.

I'm starting to wonder wether the board is defective or if I messed it up with all the soldering :/

**Comment by BenoitCaron** [comment]
So, I bought a thicker wired, rewired the power wire, both ground wires and 54MHz wire (because I still had the signal dropping issue). None of my issues have gone away: LEDs are still not blinking with HDMI connected too early, and the signal still drops after some minutes of gameplay. Could the signal dropping be caused by the board heating too much? Because I made extra careful to route the wire differently, and I can't figure out a way to have a good, reliable signal.

**Comment by ikorb** [comment]
My plan was to build a special version of GCVideo that mostly ignores the console and generates a test picture instead, however Real Life[tm] interfered.

So instead could you try flashing the Pong demo and check if it also has startup issues? If it does, it's some kind of hardware problem and I'm out of ideas.

[p2xh-pong-demo.zip](https://github.com/ikorb/gcvideo/files/4303195/p2xh-pong-demo.zip)

**Comment by BenoitCaron** [comment]
Yeah, no picture with the pong demo either. As a matter of fact, I haven't been able to get a signal with CGVideo at all since yesterday. I'm gonna try it a friend's house, on their TV, and if it doesn't work I guess I'll sell the damn thing to someone who might enjoy tinkering it. What started as a fun pet project turns out to be not so funny anymore :/

Thanks for your help by the way!

**Comment by BenoitCaron** [comment]
Well, for what it's worth, KNJN's assistance is top notch! Even though I bought the board more than 3 years ago, they told me to send it back and offered to fix it, send me a new one or refund it. I did not expect that much!

**Comment by Hattmeiny** [comment]
By any chance, could you let me know if the new board fixed everything?  Mine works fine when plugged into my tv or monitor. If I plug it into my receiver, it will just no signal with leds a constant red.

**Comment by BenoitCaron** [comment]
I didn't bother getting a new board, with the pandemic and stuff.. BUT I installed it into another GameCube, and got it to work. Kinda...
Just like you, it works fine hen connected to the TV directly, but doesn't when connected to my receiver. There is a trick to it though. I can either:
- Plug the HDMI into the GameCube after boot (after several seconds)
- Use a splitter between the GameCube and the receiver.
Both of these methods (far from ideal) allow me to use the GameCube with the receiver.

Hope that helps!

**Comment by ikorb** [comment]
If it is a very old Pluto board, it needs an extra resistor to provide 5V on a certain HDMI pin that is used by some displays and receivers to detect if a source is connected. I think KNJN added a solder jumper to later revisions that needs to be closed instead.

**Comment by Hattmeiny** [comment]
Thanks for the response.  Mine is the “D” revision so it does require the resistor. I tried with and without the 100ohm resistor and had the same issue. Starting with the revision “e” it just has a solder bridge you have to make.

Using a switch has worked fine at least.

**Comment by BenoitCaron** [comment]
I do have the resistor as well, but it doesn't help with my receiver
