### ISSUE TITLE
Video signal drops after some time

### ISSUE THREAD

**Issue by BenoitCaron** [ikorb/gcvideo#34]
Hello,

I'm having an issue with signal stability. The signal will drop while playing, more and more frequently as time goes. It might drop once after 5 minutes of playing, then 2, then 1, until the image no longer appears.

Firmware version: 3.0d

Any help would be greatly appreciated!

Regards,
Benoit

**Comment by ikorb** [comment]
Have you tried it with a different display?

**Comment by BenoitCaron** [comment]
My current setting is an Onkyo TX-NR737E receiver hooked up to my OLED55C6V LG TV.
I have only tried through the receiver as my TV supposedly won't accept DVI signals.

I'll give a try with a direct connection to the TV.

**Comment by Xaranar** [comment]
I've had similar problems when I was installing a P2X into my Wii.  It turned out the culprit was the 54MHz clock line, it tends to interfere with the other data lines so to fix the problem, I used a shielded wire to connect the clock signal.

**Comment by BenoitCaron** [comment]
No success with connecting directly to the TV, as suspected it won't take the DVI signal.
I'll try rewiring the clock signal with a different wire. How long can the wire be? It's currently less than 10 cm.

**Comment by BenoitCaron** [comment]
Tried a different wire, different routing, and I couldn't even get a picture. Sound was fine though, be the signal kept going on and off again
