### ISSUE TITLE
3.0d Failed boot on WiiDual 1.1

### ISSUE THREAD

**Issue by OFSMods** [ikorb/gcvideo#35]
Updated 2x WiiDual consoles to 3.0d today and both (one a 40 board and one a 60) are having the same issue. Both worked great before the update, and the updater verified the flash went through. 

It seems as if the WiiDual is failing during boot. The console doesn't output any video or audio whatsoever. When it's doing this, if I pull the power supply and plug it back in immediately, it will work perfectly... until you turn it off. Then when you turn it back on, it won't work until you unplug and plug it back in.

If you unplug and wait a few minutes, it won't work when you plug it back in.

Any thoughts?

**Comment by ikorb** [comment]
Immediate thought: I should never have done the Wii version, it's just a lot of trouble ;)

What version was on there before the update?

**Comment by OFSMods** [comment]
2.4c I believe, though tbh  I don't remember. It was whichever version Dan shipped the boards out with

**Comment by leonkiriliuk** [comment]
I can confirm this happened to me as well. Not only do I get black screen on HDMI but also component cables and good old composite. The blue LED light doesn’t even turn on. The board just hangs there. Moving back to 2.4 branch brought The Wii dual back to life.

**Comment by OFSMods** [comment]
Just came across my third wii with this issue. :/

**Comment by OFSMods** [comment]
I noticed that I am also having this issue on 3.0c, and am wondering if the "faster startup time" in version 3.0 is the culprit. Any chance you could add a minor delay to startup as a test? I can flash one of the faulty consoles with it to test for you if you'd like.

**Comment by ikorb** [comment]
The Wii builds were already slowed down to the previous 2.4 "as slow as possible" value in 3.0b.

**Comment by OFSMods** [comment]
Turning off Wiiconnect24 is another workaround that seems to be working, and much more liveable.

**Comment by ikorb** [comment]
Oh, I thought your problem was on initial power-on (from a red LED) and thus dismissed WC24 from the start. Does turning off WC24 fix it for all affected Wiis for you?

**Comment by ikorb** [comment]
Should also be fixed in 3.0e
