### ISSUE TITLE
Line tripling, quadrupling?

### ISSUE THREAD

**Issue by BenoitCaron** [ikorb/gcvideo#36]
Would it be possible to add a line tripling and/or line quadrupling, in order to achieve a crisper picture?
Is the Pluto IIx even capable of outputting higher resolutions?

Regards

**Comment by ikorb** [comment]
The FPGA used by GCVideo-DVI has a maximum output data rate of 640MBit/s, which limits the maximum pixel clock to 64MHz. That's just below the pixel clock needed for a 1024x768 60Hz signal (needs 65 MHz) and quite a bit below what is needed for 1280x720p60 (needs 74.25 MHz).

Additionally, the clock managers in the FPGA cannot be reconfigured at run time - the link speed for the DVI output must be set at design time. This is fortunately not a problem for the modes supported by the Gamecube, all of them run the link at the same 270MBit/s rate.
