### ISSUE TITLE
WiiDual 3.0d no signal without first removing power

### ISSUE THREAD

**Issue by mario-64** [ikorb/gcvideo#38]
I just had both of my Wii consoles upgraded from 2.4c to 3.0d. Each is connected via Denon AVR to a 4k TV - one Samsung Q60 and one LG B7A. Initially both consoles seemed to be working fine. Powered them on, enabled enhanced DVI as before. No issues.

The problem happens after power down. When either console is powered back on I get no signal on my TVs. If I unplug power then plug it back in they will boot correctly and display a screen. Basically I only get signal on first power up after removing power. This was *not* happening with 2.4c. 

Please tell me there is some setting I can change to fix this

**Comment by ikorb** [comment]
There is no setting that can fix this.

**Comment by mario-64** [comment]
> There is no setting that can fix this.

Clearly something was changed in the 3.x branch which introduced the problem. Can that change be reverted or fixed?

**Comment by mario-64** [comment]
I should add, my GCDual which is also running 3.0d does not have this problem

**Comment by ikorb** [comment]
> Clearly something was changed in the 3.x branch which introduced the problem.

Sure, but it's not an OSD setting somewhere. If I had an idea which change causes the problem, I would've fixed it already.

(and I'm currently thinking about dropping WiiDual support completely, it's a lot of hassle to support a closed-source board with open source software)

**Comment by mario-64** [comment]
> > Clearly something was changed in the 3.x branch which introduced the problem.
> 
> Sure, but it's not an OSD setting somewhere. If I had an idea which change causes the problem, I would've fixed it already.
> 
> (and I'm currently thinking about dropping WiiDual support completely, it's a lot of hassle to support a closed-source board with open source software)

This is so incredibly disappointing! I had no idea this was a known problem. I paid to have my consoles updated to fix the left-shift which was present in 2.4c. Now I basically have two unusable Wii's. I guess I'll revert back to my crappy Wii2HDMI adapters....

**Comment by mario-64** [comment]
Is it possible to downgrade to 2.4x without having to disassamble?

**Comment by ikorb** [comment]
> Is it possible to downgrade to 2.4x without having to disassamble?

No

**Comment by mario-64** [comment]
> > Is it possible to downgrade to 2.4x without having to disassamble?
> 
> No

Figures. Well, I am willing to test any possible fixes you want to try. I have two Wii's which have the issue so we can test things out

**Comment by mario-64** [comment]
Are you still troubleshooting this problem or should I find another solution for my Wii’s?

**Comment by ikorb** [comment]
Have you heard about this thing called "sleep"?

**Comment by mario-64** [comment]
No need to get testy. I was just asking if you’re still investigating or if you’ve given up on the HDMI compatibility issues

**Comment by ikorb** [comment]
When you power down your Wii, is the LED in the power button red or orange?

**Comment by mario-64** [comment]
Orange. I think it goes into standby not actual power off

**Comment by ikorb** [comment]
Ok, could you try to disable the connected standby function somewhere in your Wii setting? I think it's called WiiConnect 24 or something like that.

**Comment by mario-64** [comment]
SUCCESS!!! That was it. Disabling Wii Connect 24 fixes it. When I power off the Wii now the light is red. So there must be some sort of HDMI issue when it wakes from standby as opposed to power off. Thank you again!

**Comment by ikorb** [comment]
I'm not sure which parts of the Wii stay powered when it is in the connected standby state, but I suspect the FPGA stays at least partially powered and it then fails to correctly reinitialize when the console is turned on again. Depending on what exactly happens, the behaviour could even change from one WiiDual board to the next.

If you worry about missing out on some feature because the connected standby is off: According to Wikipedia, WiiConnect24 has been shut down in 2013.

**Comment by mario-64** [comment]
Yeah no big deal for me. Thank you again for the help :-)

**Comment by mario-64** [comment]
BTW, totally off topic but should you ever release a new firmware how exactly do you update it on Wii? On GameCube I can just run the dol file.  Do you just go into the OSD and select firmware update?

**Comment by ikorb** [comment]
You can either run the Gamecube .dol file in Gamecube mode, e.g. using Swiss or run the Wii .dol file using the Homebrew Channel. IIRC HBC needs an additional XML file with a description to make it show up in the menu, some day I'll remember to update my build scripts to generate that as a convenient zip file with everything.

After running the .dol file the process is the same for both consoles though, start the flasher using About->Update firmware and tell it to install the update with either the controller or IR remote.

**Comment by mario-64** [comment]
Ok cool thank you
