### ISSUE TITLE
WiiDual boot issues

### ISSUE THREAD

**Issue by aleomark** [ikorb/gcvideo#39]
Hi, i did install with my friend the Wiidual board, every time i turn the Wii on it works fine for the first 3-10 minutes aprox. but then starts glitching and later the image goes black, and gets back again with glitches and black again, if you turn it off and no screen comes later...

my wii is RVL-CPU-60
and wii dual firm is version 1.1     2.4c.2

Here are pics of my install:
https://imgur.com/gallery/yVKozIC

And a video with the trouble:
https://youtu.be/FeS1JuUm0xI

Can you help me with any ideas for solving this trouble please?
Thanks for your help

**Comment by ikorb** [comment]
No, I can't help you with issues caused by closed-source modified firmware builds. Please contact your supplier for support.

**Comment by aleomark** [comment]
ok, i got it, it was a problem by using leaded soldered, it doesn't mix with lead free flex, and during the expansion can create cracked joints.

I clear it and use lead free solder. thanks anyway, very happy with your projects
