### ISSUE TITLE
How can i flash the latest update to an internal WiiDual? 

### ISSUE THREAD

**Issue by davisrayler** [ikorb/gcvideo#44]
I'm on 2.4c.2 and i would like to update to latest version but dont know how, i tried the homebrew channel option but when i hit "about" on my GCVideo the option to update is not there!!! I also own a HDMy Cube Pro and I'd like to know how to update. :)

**Comment by ikorb** [comment]
WiiDual: https://twitter.com/citrus3000psi/status/1135344287699394560

HDMy Cube Pro: https://www.youtube.com/watch?v=SRa4uy1oqPo

**Comment by davisrayler** [comment]
Thank you so much, i was able to update my HDMy Cube Pro! You're the best.
