### ISSUE TITLE
Pillarboxed 16:9 output

### ISSUE THREAD

**Issue by henke37** [ikorb/gcvideo#45]
The option to output a valid 16:9 signal where the game is pillarboxed.

Why? Because my TV is garbage and blindly assumes that the signal should be stretched to 16:9, even with that setting disabled in the OSD.

**Comment by ikorb** [comment]
That's not possible with the current hardware. TO do so, the output would need to run with a higher pixel clock than the input, using a very odd multiplication factor that cannot be generated by the current FPGA's clock generators.
