### ISSUE TITLE
Linedoubler issue

### ISSUE THREAD

**Issue by lgustavod** [ikorb/gcvideo#47]
I have a USA GameCube (NTSC) with a GCPlug like GCVideo Plug n Play 3.0, but when I apply the linedoubler in 480i mode the image in screen looks shaking in horizontal, looks the Hz is out of range maybe.

TV is a Samsung 32" LCD display model LN32C550 from Brazil.

Thanks a lot.

**Comment by Papy-G** [comment]
Linedoubling should only be used when your display doesn't support 240/288p over digital link, or when an emulator or game outputs 240p as 480i.

You should use the progressive modes as much as possible on modern displays.
