### ISSUE TITLE
Controller not working

### ISSUE THREAD

**Issue by rimsky82** [ikorb/gcvideo#5]
Everything seems to be installed correctly, as the video through HDMI looks great (Pluto board from knjn.com).  However, when I have 94 connected for the controller, the controller in port 1 doesn't work at all.  If I disconnect 94, controller port 1 works again.

I have soldered to this point twice, both times with the same result.  Any ideas?

**Comment by ikorb** [comment]
Likely a wrong bitstream or the wrong pin on the FPGA side - most FPGA pins have pullups or pulldowns enabled and these overpower the controller signal on the Gamecube side.

**Comment by rimsky82** [comment]
Yup, it was my fault.  Had 94 and ground switched.  All hooked up and enjoying HD goodness.
