### ISSUE TITLE
Picture working ok but not sound Pluto-IIX HDMI

### ISSUE THREAD

**Issue by funtadan** [ikorb/gcvideo#51]
I am using the Pluto-IIX HDMI REV F, the picture, works but there is no sound coming out of it.  do you know what could be wrong with it?

**Comment by ikorb** [comment]
Did you turn on enhanced DVI mode?

**Comment by funtadan** [comment]
thanks, I just turned enhanced DVI mode on and now its working with sound

**Comment by ikorb** [comment]
Ah, good to have resolved this so easily. =)
