### ISSUE TITLE
GCvideo Color issue using Plasma TV

### ISSUE THREAD

**Issue by tonytheduke** [ikorb/gcvideo#52]
It looks like all the reds and blues are either completely off or simply reversed. Using GC-video via Kaico adapter on my plasma Panasonic TV (panasonic th-50ph11uk). I only have had this issue on this TV and tried 3 different GCvideos so I know there is a compatibility issue.

**Comment by ikorb** [comment]
Which GCVideo version is that?

**Comment by tonytheduke** [comment]
3.0d

**Comment by ikorb** [comment]
Compatibility problems like this one are unfortunately really hard to diagnose remotely. Could you try a few things to see if you can find a combination of the options below with correct colors?

* set the "X position" in the picture submenu to 0 or 1
* set the horizontal screen position in the Gamecube's own options to 0 or 1
* turn "Fix resolution" in the advanced submenu on or off
* turn "Fix sync timing" in the advanced submenu on or off
* set "Digital color format" in the advanced submenu to RGB-L oder YC444

**Comment by GizmoTheGreen** [comment]
photos might help.

**Comment by ikorb** [comment]
I'm pretty sure that I know how a Cb/Cr-swapped picture looks like.

**Comment by GizmoTheGreen** [comment]
it would help confirm it's indeed what his issue is and it would help future googles identify it's the issue they're having and possible fix, if he reports what solved it.

**Comment by tonytheduke** [comment]
Hey everyone, sorry for the late update. So I'm assuming at this point it's a compatibility issue on the Panasonic TV, which it actually more like a plasma monitor. I ordered a Mclassic upscaled in hopes it decides the image into a format the tv/monitor correctly understands. 

I also misspoke earlier when I said the software was 3.0d, it's actually v2.4 but unfortunately there is no way to update the Kaico adapter to see if that would fix it. 

I will keep you guys posted.

**Comment by ikorb** [comment]
Ah, that changes everything. If you're still on 2.4 then it is very likely that updating to 3.0d will fix it.

**Comment by GizmoTheGreen** [comment]
> Hey everyone, sorry for the late update. So I'm assuming at this point it's a compatibility issue on the Panasonic TV, which it actually more like a plasma monitor. I ordered a Mclassic upscaled in hopes it decides the image into a format the tv/monitor correctly understands.
> 
> I also misspoke earlier when I said the software was 3.0d, it's actually v2.4 but unfortunately there is no way to update the Kaico adapter to see if that would fix it.
> 
> I will keep you guys posted.

Hopefully there is either SPI or jtag pinout on Kaico(this one is new to me) adapter. programmers are kind of cheap on ebay.
jtag adapter or spi flash programmer.
I've never heard of it but all other adapters break some programming feature out. once you're on 3.0x you can update via homebrew dols.

wether you fix your issue with the mclassic or not it would be nice having it updated for the future, imho.
