### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by TH3GOD88** [ikorb/gcvideo#56]
Okay, so I looked up to get a better feel for what needs to go where and I found this diagram with photos, but it says "Connect DDC +5 to VUNREG with a 100Ohm resistor" and then right under it, it says "Connect 5V from GameCube to the VUNREG". So my question is do I need to run two 5V lines?

Here is the link.       https://drive.google.com/file/d/1mTW3C0UQoiaa0B43qtbWj6go7RphPaVX/view

**Comment by ikorb** [comment]
Older versions of the Pluto IIx-HDMI board had a solder point labelled "DDC +5", which needs to be connected to 5V from anywhere (e.g. from VUNREG) via a 100 Ohm resistor. I heard that newer ones have that resistor integrated and just need a solder jumper closed, but I don't have such a board at hand to verify.

**Comment by TH3GOD88** [comment]
I have tried so many ways and I get no video on any TV or monitor. I get power to the board, once I turn the GameCube on, I get a flash of the logo and then no signal.

**Comment by Bakuku** [comment]
> Older versions of the Pluto IIx-HDMI board had a solder point labelled "DDC +5", which needs to be connected to 5V from anywhere (e.g. from VUNREG) via a 100 Ohm resistor. I heard that newer ones have that resistor integrated and just need a solder jumper closed, but I don't have such a board at hand to verify.

Jumper? Where?

**Comment by ikorb** [comment]
As I said, I don't have one of the newer boards. Check with the manufacturer.
