### ISSUE TITLE
GCVideo is compatible with Wii Mini as well!

### ISSUE THREAD

**Issue by webhdx** [ikorb/gcvideo#57]
Hey,
Thought I'd share this if anyone wondered. You can install GCVideo to Wii Mini. I used Arthrimus board (https://github.com/Arthrimus/Wii-HDMI) and it works almost perfectly. You need to remove one cap to be able to lay the board flat on the mainboard. My Wii Mini has RVO-CPU-01 motherboard.

![IMG_2438](https://user-images.githubusercontent.com/10212760/100927047-9f049e80-34e4-11eb-84a0-97b3710727dc.JPG)
![IMG_2434](https://user-images.githubusercontent.com/10212760/100927060-a166f880-34e4-11eb-9dc4-235196f90b83.JPG)

In order to enable full potential it's required to install Wii System Menu to enable 480p.

**Comment by ikorb** [comment]
Oh, neat. Thanks for the info!
