### ISSUE TITLE
HDR support?

### ISSUE THREAD

**Issue by GK6475** [ikorb/gcvideo#58]
I have a TV that supports HDR, could you somehow implement HDR for Gcvideo? I'm sure Gamecube/Wii gamew would look amazing in HDR.

**Comment by ikorb** [comment]
Doesn't your TV have a "make my SDR content fake HDR" mode?

**Comment by GK6475** [comment]
> Doesn't your TV have a "make my SDR content fake HDR" mode?

I don't think so. It is an LG CX77 OLED 4K TV. It has an HDR effect option but that dulls color a lot.

**Comment by ikorb** [comment]
That's probably the best result you can expect from a console that does not render in HDR natively.
