### ISSUE TITLE
Testing self-made Board

### ISSUE THREAD

**Issue by drandreas** [ikorb/gcvideo#59]
I've built a board based on the Shuriken Video v3 Schematic. I would like to test the HDMI-Output before fitting the board into my console.

Looking at the HDL, I get the impression that all internal clocks are generated from the 54 MHz GC/Wii clock on input P43. Is there an option to setup the FPGA to use an internal clock instead?

**Comment by ikorb** [comment]
The Spartan 3A does not have any internal clocks that can be used to run the main logic. Even if you supply an external clock, you would still not get anything on the HDMI output because the video data from the console is missing.

**Comment by drandreas** [comment]
Thank your for the quick reply.

I wasn't expecting to see a colourful mario. My intention was to check the eye pattern of the clock/datelines lines on my dso.
