### ISSUE TITLE
No native 480p ?

### ISSUE THREAD

**Issue by idtjes3** [ikorb/gcvideo#6]
Hello. I purchased a Pluto-II ( Rev C) with gcvideo installed. Everything appears to be working fine (audio, 480i video+LD, OSD), but I cannot get native 480p games to display in progressive scan. Games that require 'B' do not respond to the command and games that have the option in the menus are greyed out. Have test on 3 different TVs with 2 different HDMI cables same results. I have also tried reflashing the board with the latest firmware. Thoughts on what to check?

**Comment by ikorb** [comment]
There are two likely issues:
1) Other Settings -> Allow 480p mode is set to "no"
2) The wiring for the cable detect pin is missing or incorrect.

**Comment by idtjes3** [comment]
Hello thanks for your response. I'm pretty sure 'allow 480p mode' is still on since the FAQ says to leave it alone. I will re double check the cable detect pin but last I checked with the multimeter I was getting a good connection. Is there a voltage range or anything like that on this pin I can use to verify a proper signal from the cube?

**Comment by ikorb** [comment]
You should see around 3.3V on that pin, coming from the FPGA.
