### ISSUE TITLE
No signal in 4K QLED Samsung Q70R series

### ISSUE THREAD

**Issue by deejaykruger** [ikorb/gcvideo#60]
Hi friend!
I have no signal when I try to connect in my 55” Samsung 4K. Tv says: resolution no allowed, change resolution for in your external device. 
I tried every resolutions (while, I plugged vía scart in another tv to do this) but nothing makes working. 
I try in HD and Full HD TVs and I had not any problem. 
Do you have any idea to use GC Video in this tv 4K set?
Thanks in advance!!

**Comment by ikorb** [comment]
Make sure that "Fix resolution" and "Fix sync timing" are turned ON in the advanced options. If you don't have these options, find a way to upgrade your device to the current version. If you already are on a 3.x version, I have no idea.

Also, a quick web search suggests that some Samsung TVs have inconsistend HDMI inputs where certain signals are accepted on some inputs but not others, so you could try using a different input on your TV.

**Comment by deejaykruger** [comment]
Worked perfectly with your recommendations. Thanks a lot!!

**Comment by deejaykruger** [comment]
Worked perfectly. Thanks
