### ISSUE TITLE
Request: GBI 486p crop to 480p via HDMI on GCDual

### ISSUE THREAD

**Issue by jeffqchen** [ikorb/gcvideo#63]
Hi,

I tried using GBI on my DOL-001 with GCDual and found out that the 486p signal it outputs from the HDMI port freaks out my TV. If I use analog RGBs through OSSC, it's cropped to 480p and my TV works.

I checked the GCVideo UI and noticed that 486p was passed through. None of the resolution settings would handle the 486p generated by GBI.

I wonder if it's possible for GCVideo to identify 486p, then crop it down to standard 480p. Thanks.

**Comment by ikorb** [comment]
Now possible in GCVideo 3.1

**Comment by jeffqchen** [comment]
> Now possible in GCVideo 3.1

Thank you!!
