### ISSUE TITLE
Request: off-standard forced H-resolution or passthrough option

### ISSUE THREAD

**Issue by Papy-G** [ikorb/gcvideo#64]
Would it be possible to get an option to disable the 720Px forced Horizontal resolution, so people with low res 4/3 displays can access Pixel perfect modes easily instead of having to deal with splitted pixels and stretched image and black bars when trying to get 640x480 on a 640x480panel, for example?

**Comment by ikorb** [comment]
You could just set Advanced->Fix resolution to "off" - it won't help you with games that output more than 640 pixels horizontally and it will not be pixel-perfect for games that internally render at an even lower resolution than the one they send to the output.

**Comment by ChipsLabs** [comment]
I also have a 640x480 panel. When playing native 480p games and enable scanlines, i got pixel perfect image.
But when I play a forced 480p games (ex F-Zero GX) scanlines are not pixel perfect. 
Is there any recommandations to fix that ?

Thanks

**Comment by ChipsLabs** [comment]
See the scanlines difference
![image](https://user-images.githubusercontent.com/104869127/202844174-1f4a36af-ebdd-4425-9b9a-8fe29293092c.jpeg)
![image](https://user-images.githubusercontent.com/104869127/202844182-29182ae8-31a3-4e49-bec3-b74174b87785.jpeg)

**Comment by Papy-G** [comment]
Isn't that more related to internal game resolution, than forced 480p or not?

**Comment by ChipsLabs** [comment]
I'm not expert on this. But when the game is forced 480p i have 448p resolution. 
So is a kind of fake 480p ?

Thanks

**Comment by ChipsLabs** [comment]
Btw i love the results of GC video !
![image](https://user-images.githubusercontent.com/104869127/202861168-e50eaf35-569b-4e7d-987e-456769f04cfa.jpeg)

**Comment by ikorb** [comment]
Your very incomplete screenshot fortunately includes the vertical part of the output resolution - one of them is 480p and one is just 448p. It's really not surprising that your display does not do pixel-exact display for a resolution that does not match its native resolution.

**Comment by ChipsLabs** [comment]
So If the resolution is 640 x 448p i should have black bar up and down of the image ?
Here ![image](https://user-images.githubusercontent.com/104869127/202862715-1e11824c-857b-414f-9def-a89ca6e130bf.jpeg)
But here I have full screen. 

Do you know how to get native resolution (with black bars) ?
Is it on swiss side ?
Then if I find this I should have perfect scanlines

Thanks

**Comment by ikorb** [comment]
I'm sorry, please ask your monitor's manufacturer or seller for support, this has nothing to do with GCVideo.
