### ISSUE TITLE
Pluto-IIx XC3S200 with the HDMI adapter board

### ISSUE THREAD

**Issue by CallyPicky42** [ikorb/gcvideo#68]
Hello.
The problem with the Pluto-IIx XC3S200 HDMI board is, the HDMI port is not where I want so could it be possible to use a Pluto-IIx XC3S200 with the HDMI adapter board programed with gcvideo!!??
Regards,
Jude

**Comment by ikorb** [comment]
I recommend using a board made specifically for the Gamecube/Wii instead of the ones from KNJN.

It is likely that you will need to modify GCVideo to use different FPGA pins if you want to use it on a different board. I cannot provide any support for that.
