### ISSUE TITLE
More fixed resolution options?

### ISSUE THREAD

**Issue by GK6475** [ikorb/gcvideo#69]
I noticed that, when a game runs in 640x448, and the fix resolution option is turned on, the image is squished into 720x480. I think that there should be an option added to choose multiple forced resolutions, like 640x480 and 704x480, or an option to force vertically only.

**Comment by ikorb** [comment]
If the image looks squished to you, it was intended to look that way by the developer. On the console's original analog output there is no distinction between unrendered and black pixels, the display will always see a signal that it will interpret as 720x480.
