### ISSUE TITLE
Sound ringing/stuttering in high pitched sounds

### ISSUE THREAD

**Issue by GK6475** [ikorb/gcvideo#71]
I've noticed that the digital audio seems to have some ringing/stuttering in some games that have high pitched sounds. Is this a problem with my GameCube, or are more people having this problem?

**Comment by ikorb** [comment]
Did you by any chance turn on the "Sample rate hack" option in the Advanced Options menu?

**Comment by GK6475** [comment]
Yes, is that the problem?

**Comment by ikorb** [comment]
Yes, that option forces the audio sample rate to exactly 48000 Hz by occasionally dropping one sample, which can create audible artifacts.

**Comment by GK6475** [comment]
Ok, thank you! That solved my problem.
