### ISSUE TITLE
Build error when running "build-all.sh"

### ISSUE THREAD

**Issue by rapperskull** [ikorb/gcvideo#72]
I set up the build environment, but I get the following error when running `build-all.sh`:

> Timing Score: 1010 (Setup: 0, Hold: 1010, Component Switching Limit: 0)
> 
> WARNING:Par:468 - Your design did not meet timing.  The following are some suggestions to assist you to meet timing in
>    your design.
> 
>    Review the timing report using Timing Analyzer (In ISE select "Post-Place &
>    Route Static Timing Report"). Go to the failing constraint(s) and evaluate the failing paths for each constraint.
> 
>    Try the Design Goal and Strategies for Timing Performance(In ISE select Project -> Design Goals & Strategies) to
>    ensure the best options are set in the tools for timing closure.
> 
>    Use the Xilinx "SmartXplorer" script to try special combinations of
>    options known to produce very good results.
> 
>    Visit the Xilinx technical support web at http://support.xilinx.com and go to
>    either "Troubleshoot->Tech Tips->Timing & Constraints" or "
>    TechXclusives->Timing Closure" for tips and suggestions for meeting timing
>    in your design.
> 
> Asterisk (*) preceding a constraint indicates it was not met.
>    This may be due to a setup or hold violation.
> 
> ----------------------------------------------------------------------------------------------------------
>   Constraint                                |    Check    | Worst Case |  Best Case | Timing |   Timing   
>                                             |             |    Slack   | Achievable | Errors |    Score   
> ----------------------------------------------------------------------------------------------------------
> * TS_Inst_Datapipe_Inst_ClockGen_vdcm_clk0  | SETUP       |     0.005ns|    18.503ns|       0|           0
>   = PERIOD TIMEGRP         "Inst_Datapipe_I | HOLD        |    -1.010ns|            |       1|        1010
>   nst_ClockGen_vdcm_clk0" TS_CLOCK_54 HIGH  |             |            |            |        |            
>   50%                                       |             |            |            |        |            
> ----------------------------------------------------------------------------------------------------------
>   TS_Inst_Datapipe_Inst_ClockGen_adcm_clkfx | SETUP       |     0.424ns|     5.748ns|       0|           0
>    = PERIOD TIMEGRP         "Inst_Datapipe_ | HOLD        |     1.084ns|            |       0|           0
>   Inst_ClockGen_adcm_clkfx" TS_CLOCK_54 * 3 |             |            |            |        |            
>    HIGH 50%                                 |             |            |            |        |            
> ----------------------------------------------------------------------------------------------------------
>   TS_Inst_Datapipe_Inst_ClockGen_vdcm_clkfx | SETUP       |     0.580ns|     6.396ns|       0|           0
>    = PERIOD TIMEGRP         "Inst_Datapipe_ | HOLD        |     0.946ns|            |       0|           0
>   Inst_ClockGen_vdcm_clkfx" TS_CLOCK_54 * 2 |             |            |            |        |            
>   .5 HIGH 50%                               |             |            |            |        |            
> ----------------------------------------------------------------------------------------------------------
>   TS_Inst_Datapipe_Inst_ClockGen_vdcm_clkfx | SETUP       |     1.794ns|     3.818ns|       0|           0
>   180 = PERIOD TIMEGRP         "Inst_Datapi | HOLD        |     4.184ns|            |       0|           0
>   pe_Inst_ClockGen_vdcm_clkfx180" TS_CLOCK_ |             |            |            |        |            
>   54 * 2.5 PHASE         3.7037037 ns HIGH  |             |            |            |        |            
>   50%                                       |             |            |            |        |            
> ----------------------------------------------------------------------------------------------------------
>   TS_CLOCK_54 = PERIOD TIMEGRP "CLOCK_54" 5 | SETUP       |    12.977ns|     5.541ns|       0|           0
>   4 MHz HIGH 50%                            | HOLD        |     1.267ns|            |       0|           0
>                                             | MINLOWPULSE |    12.518ns|     6.000ns|       0|           0
> ----------------------------------------------------------------------------------------------------------
>   COMP "VData<7>" OFFSET = IN 5 ns VALID 12 | SETUP       |     7.103ns|    -2.103ns|       0|           0
>    ns BEFORE COMP "VClockN" LOW             | HOLD        |     3.039ns|            |       0|           0
> ----------------------------------------------------------------------------------------------------------
>   COMP "VData<4>" OFFSET = IN 5 ns VALID 12 | SETUP       |     7.355ns|    -2.355ns|       0|           0
>    ns BEFORE COMP "VClockN" LOW             | HOLD        |     2.844ns|            |       0|           0
> ----------------------------------------------------------------------------------------------------------
>   COMP "VData<5>" OFFSET = IN 5 ns VALID 12 | SETUP       |     7.399ns|    -2.399ns|       0|           0
>    ns BEFORE COMP "VClockN" LOW             | HOLD        |     2.802ns|            |       0|           0
> ----------------------------------------------------------------------------------------------------------
>   COMP "VData<3>" OFFSET = IN 5 ns VALID 12 | SETUP       |     7.403ns|    -2.403ns|       0|           0
>    ns BEFORE COMP "VClockN" LOW             | HOLD        |     2.806ns|            |       0|           0
> ----------------------------------------------------------------------------------------------------------
>   COMP "VData<6>" OFFSET = IN 5 ns VALID 12 | SETUP       |     7.420ns|    -2.420ns|       0|           0
>    ns BEFORE COMP "VClockN" LOW             | HOLD        |     2.772ns|            |       0|           0
> ----------------------------------------------------------------------------------------------------------
>   COMP "VData<2>" OFFSET = IN 5 ns VALID 12 | SETUP       |     7.434ns|    -2.434ns|       0|           0
>    ns BEFORE COMP "VClockN" LOW             | HOLD        |     2.774ns|            |       0|           0
> ----------------------------------------------------------------------------------------------------------
>   COMP "VData<0>" OFFSET = IN 5 ns VALID 12 | SETUP       |     7.777ns|    -2.777ns|       0|           0
>    ns BEFORE COMP "VClockN" LOW             | HOLD        |     2.468ns|            |       0|           0
> ----------------------------------------------------------------------------------------------------------
>   COMP "VData<1>" OFFSET = IN 5 ns VALID 12 | SETUP       |     8.005ns|    -3.005ns|       0|           0
>    ns BEFORE COMP "VClockN" LOW             | HOLD        |     2.286ns|            |       0|           0
> ----------------------------------------------------------------------------------------------------------
>   COMP "CSel" OFFSET = IN 5 ns VALID 12 ns  | SETUP       |     8.021ns|    -3.021ns|       0|           0
>   BEFORE COMP "VClockN" LOW                 | HOLD        |     2.268ns|            |       0|           0
> ----------------------------------------------------------------------------------------------------------
>   TS_Audio = MAXDELAY FROM TIMEGRP "MC_AUDI | SETUP       |    26.256ns|    10.781ns|       0|           0
>   O" TO TIMEGRP "MC_AUDIO" TS_CLOCK_54      | HOLD        |     0.798ns|            |       0|           0
>       / 2                                   |             |            |            |        |            
> ----------------------------------------------------------------------------------------------------------
> 
> 
> Derived Constraint Report
> Review Timing Report for more details on the following derived constraints.
> To create a Timing Report, run "trce -v 12 -fastpaths -o design_timing_report design.ncd design.pcf"
> or "Run Timing Analysis" from Timing Analyzer (timingan).
> Derived Constraints for TS_CLOCK_54
> +-------------------------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
> |                               |   Period    |       Actual Period       |      Timing Errors        |      Paths Analyzed       |
> |           Constraint          | Requirement |-------------+-------------|-------------+-------------|-------------+-------------|
> |                               |             |   Direct    | Derivative  |   Direct    | Derivative  |   Direct    | Derivative  |
> +-------------------------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
> |TS_CLOCK_54                    |     18.519ns|      6.000ns|     18.503ns|            0|            1|           80|      1006747|
> | TS_Audio                      |     37.037ns|     10.781ns|          N/A|            0|            0|         2029|            0|
> | TS_Inst_Datapipe_Inst_ClockGen|     18.519ns|     18.503ns|          N/A|            1|            0|      1003957|            0|
> | _vdcm_clk0                    |             |             |             |             |             |             |             |
> | TS_Inst_Datapipe_Inst_ClockGen|      7.407ns|      6.396ns|          N/A|            0|            0|          372|            0|
> | _vdcm_clkfx                   |             |             |             |             |             |             |             |
> | TS_Inst_Datapipe_Inst_ClockGen|      7.407ns|      3.818ns|          N/A|            0|            0|            4|            0|
> | _vdcm_clkfx180                |             |             |             |             |             |             |             |
> | TS_Inst_Datapipe_Inst_ClockGen|      6.173ns|      5.748ns|          N/A|            0|            0|          385|            0|
> | _adcm_clkfx                   |             |             |             |             |             |             |             |
> +-------------------------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
> 
> 1 constraint not met.
> 
> 
> Generating Pad Report.
> 
> All signals are completely routed.
> 
> Total REAL time to PAR completion: 55 secs 
> Total CPU time to PAR completion: 55 secs 
> 
> Peak Memory Usage:  650 MB
> 
> Placer: Placement generated during map.
> Routing: Completed - No errors found.
> Timing: Completed - 1 errors found.
> 
> Number of error messages: 0
> Number of warning messages: 1
> Number of info messages: 1
> 
> Writing design to file toplevel_shuriken.ncd
> 
> 
> 
> PAR done!
> make[1]: *** [scripts/Makefile.common:233: build/main-shuriken-v3-gc/toplevel_shuriken.ncd] Errore 1
> make[1]: uscita dalla directory «/home/rapperskull/gcvideo/HDL/gcvideo_dvi»
> make: *** [Makefile:152: build/main-shuriken-v3-gc/toplevel_shuriken.bin] Errore 2

I don't get the same error if I manually run `make TARGET=shuriken-v3-gc` after the failure.

**Comment by ikorb** [comment]
Ah, I guess I forgot to commit the correct cost table used for the release build. Try changing the COST_TABLE value in scripts/Makefile.common and try again - the valid range is from 1 to 100, it modifies some heuristics in the synthesis process that can make the difference between failing or making the required timing.

Alternatively you can use the make invocation you mentioned after the failure because the Makefile is written to force a stop in case of problems, but it does not remove the output files and another invocation will just continue with the next step. There is a chance that timing errors result in audio or video artifacts though.

**Comment by rapperskull** [comment]
I modified the script to avoid deleting the build folder, so that I can simply re-run it. I'm going to use the gcplug target I guess, so I won't be affected by the glitches.

**Comment by rapperskull** [comment]
BTW setting COST_TABLE to 4 solves the issue.
