### ISSUE TITLE
GC Dual on 3.0d/3.0e unable to update to 3.0e nor 3.1 using DOL

### ISSUE THREAD

**Issue by mmcgann** [ikorb/gcvideo#83]
Just finished a clean install of the GC Dual from Castlemania Games. Hardware came flashed with 3.0d. Debug menu shows clean except for AData which fluctuates a bit from (500-600)but says "Probably Okay?"

Putting the GCVideo into Firmware Update mode yields the same result for both versions using the DOL method. "No compatible firmware found"

My older GC w/ a fairly early GC Dual from Dan, I had manually flashed to 3.0e (works fine) but also fails to upgrade to 3.1 using the DOL  with the message "No firmware for "DK02" found". Debug menu looks the same None/OK/"Probably Okay" (500-600)

Any insights would be appreciated. Both cubes work perfectly otherwise.

**Comment by drandreas** [comment]
Dan did for some reason change the board identifiers, see also #77.

**Comment by ikorb** [comment]
Please contact your vendor for a compatible firmware update.

**Comment by lain32** [comment]
I updated to 3.0e on my GCDual before but now I'm getting the same problem for 3.1.
I was getting this problem for 3.0e but somehow got it working... not sure what I did before. (I've tried both FW)
