### ISSUE TITLE
JTAG does not support XSVF Files / Pluto IIx 

### ISSUE THREAD

**Issue by Bartl1984** [ikorb/gcvideo#90]
Hello everyone, hope someone can help me...
Namely, wanted to update my Pluto IIx firmware from 2.4 to 3.0d. Unfortunately, this is only possible with a flasher.
I tried following this guide and everything worked fine so far. Until you choose the file... Unfortunately, UrJTAG does not support XSVF files. According to the instructions, there was apparently also an SVF file. Can someone create the right file? Thanks in advance!
[ GCVideo 3.0d Pluto IIx board FW update with cheap USBBlaster](https://shmups.system11.org/viewtopic.php?t=66428)

Unfortunately I don't own the official KNJN update board...

**Comment by ikorb** [comment]
Completely untested:

[gcvideo-dvi-p2xh-gc-3.1-M25P40-complete.svf.zip](https://github.com/ikorb/gcvideo/files/8645890/gcvideo-dvi-p2xh-gc-3.1-M25P40-complete.svf.zip)

**Comment by Bartl1984** [comment]
Hello, thank you very much!  It worked immediately!  How can I show my appreciation to them?  Thanks!
