### ISSUE TITLE
Analog Output is Very Washed Out

### ISSUE THREAD

**Issue by GK6475** [ikorb/gcvideo#91]
When I attempt to use Component or SCART RGB from my GCHD, the colors are very washed out. I tried both YPbPr, RGB, and RGBs, with the same results. I tried this on both an old TV and Retrotink-5X, with the same results. I made sure that the black levels were set correctly, so that is not the issue. These issues only occur over analog, digital is fine. Also, this happened with two seperate GCHDs, and yet I cannot find any reports of this issue elsewhere. The reason why I am putting this up is because I think it may be a software problem. Here is an example, with Analog being the washed out image:
![20220520_164212](https://user-images.githubusercontent.com/75499860/169616463-4db86eec-7e76-4937-a307-d15a376eb83c.jpg)
![20220520_164151](https://user-images.githubusercontent.com/75499860/169616482-efbe0252-e1e8-4388-a016-c22cbd6b97c5.jpg)

**Comment by ikorb** [comment]
Something seems to be wrong with your white level, not your black level?

If the digital output works for you, use it? The analog stuff is just a "it wasn't much work to add it" thing, but it is not the main focus and by its nature it will always be inferior.

**Comment by GK6475** [comment]
Okay. That is fine. I was using an HDMI to component converter anyways, just wanted to know if this could be solved, so that my cables weren't so messy.
